version: '3.1'
services:
    db:
      image: mysql:8.0.28
      container_name: metadata_mysql
      #command: --default-authentication-plugin=mysql_native_password
      #restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3306:3306"
      volumes:
        - ./metadata_mysql-initialization:/docker-entrypoint-initdb.d
        - metadata_db:/var/lib/mysql

volumes:
  metadata_db: