spring:
  datasource:
    url: jdbc:mysql://localhost:3306/metadata_db?userSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRerieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none